In [13]:
import sys

import torch
import numpy as np

from torch.utils.data import DataLoader

sys.path.append(r'F:\time_step\OfflineRL_FactoredActions')
from RL_mimic_sepsis.d_BCQ.src.evaluate import EpisodicBufferO

In [14]:
val_episodes_O = EpisodicBufferO(128, 25, 81)
action_space = 'NormThreshold'
timestep = 4
dataset_tyepe = 'val'

val_episodes_O.load(
    f'F:/time_step/OfflineRL_FactoredActions/RL_mimic_sepsis/'
    rf'data/data_as{action_space}_dt{timestep}h'
    f'/episodes+encoded_state+knn_pibs/{dataset_tyepe}_data.pt')

tmp_val_episodes_loader_O = DataLoader(val_episodes_O, batch_size=len(val_episodes_O), shuffle=False)
val_batch_O = next(iter(tmp_val_episodes_loader_O))

Episodic Buffer loaded with 2757 episides.


In [15]:
len(val_batch_O)

6

In [16]:
_, action, _, _, pibs, estm_pibs = val_batch_O
pibs.shape, estm_pibs.shape

(torch.Size([2757, 20, 25]), torch.Size([2757, 20, 25]))

In [17]:
action[6, 2]

tensor([10])

In [18]:
# torch.set_printoptions(sci_mode=False, precision=3)
pibs[2, 6, :]

tensor([1.4588e-05, 5.6630e-07, 8.6063e-08, 1.3192e-07, 1.3091e-07, 1.8365e-05,
        4.7193e-07, 2.1403e-07, 7.0754e-07, 2.6571e-07, 9.9996e-01, 4.3060e-08,
        0.0000e+00, 1.3561e-07, 4.4175e-08, 1.0895e-06, 8.6567e-08, 4.3224e-08,
        8.4431e-08, 1.2612e-07, 1.7213e-07, 4.3221e-08, 8.4521e-08, 0.0000e+00,
        4.2155e-08])

In [19]:
estm_pibs[2, 6, :]

tensor([3.5090e-01, 6.3794e-03, 1.4852e-03, 1.9328e-03, 0.0000e+00, 4.9665e-01,
        1.2371e-02, 9.0466e-03, 1.2878e-02, 8.5257e-03, 5.8358e-02, 1.9727e-03,
        2.4763e-03, 1.0060e-03, 4.9235e-04, 2.2030e-02, 4.7991e-04, 9.8751e-04,
        2.5193e-03, 2.9269e-03, 3.5692e-03, 0.0000e+00, 0.0000e+00, 1.0013e-03,
        2.0128e-03])

In [20]:
argmax_idx_pibs = torch.argmax(pibs, dim=-1) 
counts_pibs = torch.bincount(argmax_idx_pibs.flatten(), minlength=25)
counts_pibs

tensor([29719,   116,    47,    49,    98, 16223,   788,   663,   616,   505,
         2996,   157,   161,   200,   160,  1363,   102,   149,   208,   184,
          282,    40,    70,   104,   140])

In [21]:
counts_action = torch.bincount(action.flatten(), minlength=25)
counts_action

tensor([29719,   116,    47,    49,    98, 16223,   788,   663,   616,   505,
         2996,   157,   161,   200,   160,  1363,   102,   149,   208,   184,
          282,    40,    70,   104,   140])

In [22]:
argmax_idx_estm_pibs = torch.argmax(estm_pibs, dim=-1) 
counts_estm_pibs = torch.bincount(argmax_idx_estm_pibs.flatten(), minlength=25)
counts_estm_pibs

tensor([27855,     0,     0,     0,     0, 27285,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0])